# -*- coding: utf-8 -*-
"""app_1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qnBqgYFRMYWnSEtQ0m9sunj22DNL1-vh
"""



import streamlit as st
import pandas as pd
import geopandas as gpd
import folium
from folium.plugins import MarkerCluster
from streamlit_folium import st_folium
from shapely.geometry import Point

st.set_page_config(page_title="Property Preservation Dashboard", layout="wide")

st.title("🏠 GIS-Integrated Property Preservation Dashboard")
st.subheader("🔍 Zoom in/out and click on any property to see its details")


# --- Admin upload section ---
st.sidebar.header("Admin Controls")
uploaded_file = st.sidebar.file_uploader("Upload updated CSV", type=["csv"])

if uploaded_file:
    df = pd.read_csv(uploaded_file)
    df.to_csv("properties.csv", index=False)
    st.sidebar.success("✅ File updated successfully!")
else:
    df = pd.read_csv("properties.csv")

st.sidebar.title("📂 Resources")

sections = ["VRM", "Cyprex", "Pricing", "Other"]
selected_section = st.sidebar.selectbox("Select Section", sections)

# Admin upload
st.sidebar.markdown("### Upload a file")
uploaded_resource = st.sidebar.file_uploader(f"Upload file to {selected_section}", type=["pdf", "docx", "xlsx", "csv", "txt"])

if uploaded_resource:
    save_path = f"resources/{selected_section}_{uploaded_resource.name}"
    with open(save_path, "wb") as f:
        f.write(uploaded_resource.getbuffer())
    st.sidebar.success(f"✅ File uploaded to {selected_section} section!")

    

# --- Convert to GeoDataFrame ---
gdf = gpd.GeoDataFrame(
    df, geometry=[Point(xy) for xy in zip(df["longitude"], df["latitude"])], crs="EPSG:4326"
)

# --- Create Map ---
m = folium.Map(location=[gdf.geometry.y.mean(), gdf.geometry.x.mean()], zoom_start=13, tiles="CartoDB positron")

status_colors = {
    "Vacant": "red",
    "Secured": "blue",
    "In Progress": "orange",
    "Completed": "green"
}

marker_cluster = MarkerCluster().add_to(m)

for _, row in gdf.iterrows():
    popup = f"""
    <b>ID:</b> {row['id']}<br>
    <b>Address:</b> {row['address']}<br>
    <b>Status:</b> {row['status']}<br>
    <b>Vendor:</b> {row['vendor']}<br>
    <b>Notes:</b> {row['notes']}
    """
    folium.CircleMarker(
        location=[row.geometry.y, row.geometry.x],
        radius=6,
        color=status_colors.get(row["status"], "gray"),
        fill=True,
        fill_color=status_colors.get(row["status"], "gray"),
        fill_opacity=0.9,
        popup=folium.Popup(popup, max_width=250),
    ).add_to(marker_cluster)


# --- Add custom legend (HTML injected) ---
legend_html = """
<div style="
    position: fixed; 
    bottom: 40px; left: 40px; width: 180px; height: 130px; 
    background-color: white; 
    border:2px solid grey; 
    z-index:9999; 
    font-size:14px; 
    border-radius:8px;
    padding:10px;
    box-shadow:2px 2px 5px rgba(0,0,0,0.3);
">
<b>Status Legend</b><br>
<span style="color:red;">&#9679;</span> Vacant<br>
<span style="color:blue;">&#9679;</span> Secured<br>
<span style="color:orange;">&#9679;</span> In Progress<br>
<span style="color:green;">&#9679;</span> Completed
</div>
"""
m.get_root().html.add_child(folium.Element(legend_html))

st_folium(m, width=1300, height=650)

