# -*- coding: utf-8 -*-
"""app_1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qnBqgYFRMYWnSEtQ0m9sunj22DNL1-vh
"""



import streamlit as st
import pandas as pd
import geopandas as gpd
import folium
from folium.plugins import MarkerCluster
from streamlit_folium import st_folium
from shapely.geometry import Point

st.set_page_config(page_title="Property Preservation Dashboard", layout="wide")

st.title("🏠 GIS-Integrated Property Preservation Dashboard")
st.subtitle("zoom in-out and click on the properties ")

# --- Admin upload section ---
st.sidebar.header("Admin Controls")
uploaded_file = st.sidebar.file_uploader("Upload updated CSV", type=["csv"])

if uploaded_file:
    df = pd.read_csv(uploaded_file)
    df.to_csv("properties.csv", index=False)
    st.sidebar.success("✅ File updated successfully!")
else:
    df = pd.read_csv("properties.csv")

# --- Convert to GeoDataFrame ---
gdf = gpd.GeoDataFrame(
    df, geometry=[Point(xy) for xy in zip(df["longitude"], df["latitude"])], crs="EPSG:4326"
)

# --- Create Map ---
m = folium.Map(location=[gdf.geometry.y.mean(), gdf.geometry.x.mean()], zoom_start=13, tiles="CartoDB positron")

status_colors = {
    "Vacant": "red",
    "Secured": "blue",
    "In Progress": "orange",
    "Completed": "green"
}

marker_cluster = MarkerCluster().add_to(m)

for _, row in gdf.iterrows():
    popup = f"""
    <b>ID:</b> {row['id']}<br>
    <b>Address:</b> {row['address']}<br>
    <b>Status:</b> {row['status']}<br>
    <b>Vendor:</b> {row['vendor']}<br>
    <b>Notes:</b> {row['notes']}
    """
    folium.CircleMarker(
        location=[row.geometry.y, row.geometry.x],
        radius=6,
        color=status_colors.get(row["status"], "gray"),
        fill=True,
        fill_color=status_colors.get(row["status"], "gray"),
        fill_opacity=0.9,
        popup=folium.Popup(popup, max_width=250),
    ).add_to(marker_cluster)

st_folium(m, width=1300, height=650)



